# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 186)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(10, 110, 481, 41))
        self.play.setObjectName("play")
        self.pause = QtWidgets.QLineEdit(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(130, 10, 81, 20))
        self.pause.setObjectName("pause")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.label_2.setObjectName("label_2")
        self.slot_food = QtWidgets.QLineEdit(self.centralwidget)
        self.slot_food.setGeometry(QtCore.QRect(80, 40, 113, 20))
        self.slot_food.setObjectName("slot_food")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 40, 81, 21))
        self.label_3.setObjectName("label_3")
        self.slot_drink = QtWidgets.QLineEdit(self.centralwidget)
        self.slot_drink.setGeometry(QtCore.QRect(380, 40, 113, 20))
        self.slot_drink.setObjectName("slot_drink")
        self.exit_button = QtWidgets.QLineEdit(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(380, 10, 113, 20))
        self.exit_button.setObjectName("exit_button")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 10, 141, 21))
        self.label_4.setObjectName("label_4")
        self.is_rainbow_line = QtWidgets.QLineEdit(self.centralwidget)
        self.is_rainbow_line.setGeometry(QtCore.QRect(380, 70, 113, 22))
        self.is_rainbow_line.setObjectName("is_rainbow_line")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 70, 151, 20))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play.setText(_translate("MainWindow", "Запустить"))
        self.pause.setPlaceholderText(_translate("MainWindow", "5"))
        self.label.setText(_translate("MainWindow", "T между паузами"))
        self.label_2.setText(_translate("MainWindow", "  Слот Еды:"))
        self.slot_food.setPlaceholderText(_translate("MainWindow", "5"))
        self.label_3.setText(_translate("MainWindow", " Слот напитка:"))
        self.slot_drink.setPlaceholderText(_translate("MainWindow", "4"))
        self.exit_button.setPlaceholderText(_translate("MainWindow", "9"))
        self.label_4.setText(_translate("MainWindow", " Кнопка для завершения:"))
        self.is_rainbow_line.setPlaceholderText(_translate("MainWindow", "да/нет"))
        self.label_6.setText(_translate("MainWindow", "Намотана радужная леска"))
