# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 131)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(10, 70, 481, 41))
        self.play.setObjectName("play")
        self.pause = QtWidgets.QLineEdit(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(80, 10, 113, 20))
        self.pause.setObjectName("pause")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.label_2.setObjectName("label_2")
        self.food = QtWidgets.QLineEdit(self.centralwidget)
        self.food.setGeometry(QtCore.QRect(80, 40, 113, 20))
        self.food.setObjectName("food")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 40, 61, 21))
        self.label_3.setObjectName("label_3")
        self.food2 = QtWidgets.QLineEdit(self.centralwidget)
        self.food2.setGeometry(QtCore.QRect(380, 40, 113, 20))
        self.food2.setObjectName("food2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 10, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 10, 141, 21))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play.setText(_translate("MainWindow", "Запустить"))
        self.pause.setPlaceholderText(_translate("MainWindow", "80"))
        self.label.setText(_translate("MainWindow", " Пауза:"))
        self.label_2.setText(_translate("MainWindow", "  Слот Еды:"))
        self.food.setPlaceholderText(_translate("MainWindow", "5"))
        self.label_3.setText(_translate("MainWindow", " Слот Еды2:"))
        self.food2.setPlaceholderText(_translate("MainWindow", "4"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "9"))
        self.label_4.setText(_translate("MainWindow", " Кнопка для завершения:"))
