# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 265)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(20, 180, 481, 41))
        self.play.setObjectName("play")
        self.min_dx = QtWidgets.QLineEdit(self.centralwidget)
        self.min_dx.setGeometry(QtCore.QRect(80, 10, 113, 20))
        self.min_dx.setObjectName("min_dx")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 61, 21))
        self.label_2.setObjectName("label_2")
        self.slot_food = QtWidgets.QLineEdit(self.centralwidget)
        self.slot_food.setGeometry(QtCore.QRect(80, 40, 113, 20))
        self.slot_food.setObjectName("slot_food")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 40, 81, 21))
        self.label_3.setObjectName("label_3")
        self.slot_drink = QtWidgets.QLineEdit(self.centralwidget)
        self.slot_drink.setGeometry(QtCore.QRect(380, 40, 113, 20))
        self.slot_drink.setObjectName("slot_drink")
        self.n_tips = QtWidgets.QLineEdit(self.centralwidget)
        self.n_tips.setGeometry(QtCore.QRect(380, 10, 113, 20))
        self.n_tips.setObjectName("n_tips")
        self.label_n_tips = QtWidgets.QLabel(self.centralwidget)
        self.label_n_tips.setGeometry(QtCore.QRect(280, 10, 81, 21))
        self.label_n_tips.setObjectName("label_n_tips")
        self.exit_button = QtWidgets.QLineEdit(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(180, 70, 113, 22))
        self.exit_button.setObjectName("exit_button")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 151, 20))
        self.label_4.setObjectName("label_4")
        self.throw_power = QtWidgets.QLineEdit(self.centralwidget)
        self.throw_power.setGeometry(QtCore.QRect(180, 100, 113, 22))
        self.throw_power.setObjectName("throw_power")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 151, 21))
        self.label_5.setObjectName("label_5")
        self.is_rainbow_line = QtWidgets.QLineEdit(self.centralwidget)
        self.is_rainbow_line.setGeometry(QtCore.QRect(180, 130, 113, 22))
        self.is_rainbow_line.setObjectName("is_rainbow_line")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 151, 20))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play.setText(_translate("MainWindow", "Запустить"))
        self.min_dx.setPlaceholderText(_translate("MainWindow", "50"))
        self.label.setText(_translate("MainWindow", "Мин dx"))
        self.label_2.setText(_translate("MainWindow", "  Слот Еды:"))
        self.slot_food.setPlaceholderText(_translate("MainWindow", "5"))
        self.label_3.setText(_translate("MainWindow", " Слот Напитка:"))
        self.slot_drink.setPlaceholderText(_translate("MainWindow", "4"))
        self.n_tips.setPlaceholderText(_translate("MainWindow", "3"))
        self.label_n_tips.setText(_translate("MainWindow", "Кол-во удилищ"))
        self.exit_button.setPlaceholderText(_translate("MainWindow", "9"))
        self.label_4.setText(_translate("MainWindow", "Клавиша для завершения"))
        self.throw_power.setPlaceholderText(_translate("MainWindow", "57"))
        self.label_5.setText(_translate("MainWindow", "Укажите % силы броска"))
        self.is_rainbow_line.setPlaceholderText(_translate("MainWindow", "да/нет"))
        self.label_6.setText(_translate("MainWindow", "Намотана радужная леска"))
